In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
row_sum = s.sum(axis = 1)

for i in row_sum:
    if i != 45:
        print("invalid sudoku")
        break
else:
     print("valid for rows")
              


valid for rows


In [4]:
row_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [5]:
col_sum = s.sum(axis = 0)

for i in col_sum:
    if i != 45:
        print("invalid sudoku")
        break
else:
     print("valid for cols")
              

valid for cols


In [6]:
col_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [7]:
for i in range(0,8,3):
    for j in range(0,8,3):
        a = s[i:i+3, j:j+3]
        print(a.sum())

45
45
45
45
45
45
45
45
45


In [8]:
print( a.sum())

45


**General Questions**

In [9]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [10]:
#get shape of data array
data.shape


(5, 3)

In [11]:
#find average age of students
avg = data.sum(axis=0)
avg


array([ 92, 408, 416])

In [12]:
avg_age = avg[0]/5
avg_age


np.float64(18.4)

** alternative way of mean **

In [13]:
np.mean(data[: , 0])

np.float64(18.4)

In [14]:
#extract math marks of all students
data[:,1]

array([85, 92, 76, 65, 90])

In [15]:
#extract highest science marks
a = data[:,2]
a.max()
# OR np.max(data[:,2])


np.int64(95)

In [16]:
#Get details of the student who scored more than 90 in maths
data[data[:,1] > 90]



array([[19, 92, 88]])

In [17]:
#increase maths marks of all students by 5
a = data[:,1]
print(a+5)

[90 97 81 70 95]


In [18]:
#find how many students are younger than 19
age = data[data[:,0]<19]
for i in age :
    print(i)

    
len(data[data[:,0]<19])
    


[18 85 78]
[17 76 95]
[18 65 70]


3

In [19]:
#calculate avg marks in each subject(col wise)
mathmean = np.mean(data[:,1])
mathmean

np.float64(81.6)

In [20]:
sciencemean = np.mean(data[:, 2])
sciencemean

np.float64(83.2)

In [21]:
np.mean(data[:, 1:], axis =0)

array([81.6, 83.2])

In [28]:
#Get data of students who scored at least 80 in both subjects
data[(data[:,1] >= 80) & (data[:,2] >=80 )]



array([[19, 92, 88],
       [20, 90, 85]])

# very important ques


In [33]:
#replace all science marks <75 with 0
data[:,2][data[:,2]<75] = 0
data

      


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])