**NUMPY arrays**

In [1]:
import numpy as np

In [2]:
arrays = np.array([[1,2,3,4]] , np.int32)

In [3]:
arrays

array([[1, 2, 3, 4]], dtype=int32)

In [4]:
arrays.dtype

dtype('int32')

In [5]:
arrays[0,2]

np.int32(3)

In [6]:
arrays[0]

array([1, 2, 3, 4], dtype=int32)

In [7]:
arrays[0,1]

np.int32(2)

In [8]:
new_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
new_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
new_array.size

9

In [11]:
new_array.dtype

dtype('int64')

In [12]:
new_array.shape

(3, 3)

In [13]:
zrs = np.zeros((3,4))

In [14]:
zrs

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
range = np.arange(12)

In [16]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
lspace = np.linspace(1,10,5)

In [18]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
lspace = np.linspace(1,10,3)

In [20]:
lspace

array([ 1. ,  5.5, 10. ])

In [21]:
empty = np.empty((2,5))

In [22]:
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.67019898e-307, 2.67018234e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.42419530e-306]])

In [23]:
emp_like = np.empty_like(range)

In [24]:
emp_like

array([      1808234470280,                  57,                   0,
                         0,   27584981509341184, 3471831545649718635,
       3269948909094004020, 7306584814178808166, 3615604788893920564,
       3991704609024850021, 7162263158364976693, 8462385098680267893])

In [25]:
ident = np.identity(22)

In [26]:
ident

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,

In [27]:
ident.shape


(22, 22)

In [28]:
ident.size

484

In [29]:
arr = np.arange(33)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [31]:
arr.reshape(3,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [32]:
arr = np.arange(30)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
arr1 = arr.reshape(2,15)

In [35]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
arr2 = arr.reshape(3,10)

In [37]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
rav = arr2.ravel()

In [39]:
rav

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
rav.shape

(30,)

In [41]:
arr2.shape

(3, 10)

In [42]:
arr1.shape

(2, 15)

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.sum(axis=0)

array([12, 15, 18])

In [46]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [47]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])