** NUMPY arrays **

In [1]:
import numpy as np

In [2]:
arrays = np.array([[1,2,3,4]] , np.int32)

In [3]:
arrays

array([[1, 2, 3, 4]], dtype=int32)

In [4]:
arrays.dtype

dtype('int32')

In [5]:
arrays[0,2]

np.int32(3)

In [6]:
arrays[0]

array([1, 2, 3, 4], dtype=int32)

In [7]:
arrays[0,1]

np.int32(2)

In [8]:
new_array = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
new_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
new_array.size

9

In [11]:
new_array.dtype

dtype('int64')

In [12]:
new_array.shape

(3, 3)

In [13]:
zrs = np.zeros((3,4))

In [14]:
zrs

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
range = np.arange(12)

In [16]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
lspace = np.linspace(1,10,5)

In [18]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
lspace = np.linspace(1,10,3)

In [20]:
lspace

array([ 1. ,  5.5, 10. ])

In [21]:
empty = np.empty((2,5))

In [22]:
empty

array([[4.67296746e-307, 1.69121096e-306, 2.67019898e-307,
        2.67018234e-306, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.42419530e-306, 0.00000000e+000]])

In [23]:
emp_like = np.empty_like(range)

In [24]:
emp_like

array([      1649751338968,                  64,                   0,
                         0,   29555310641283072, 7005740871486552119,
       3703478652377381217, 4123106151849603383, 3631090091585463608,
       4050765095140222514, 3690196740909447009, 7364337796366283314])

In [25]:
ident = np.identity(22)

In [26]:
ident

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,

In [27]:
ident.shape


(22, 22)

In [28]:
ident.size

484

In [29]:
arr = np.arange(33)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [31]:
arr.reshape(3,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [32]:
arr = np.arange(30)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
arr1 = arr.reshape(2,15)

In [35]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
arr2 = arr.reshape(3,10)

In [37]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
rav = arr2.ravel()

In [39]:
rav

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [40]:
rav.shape

(30,)

In [41]:
arr2.shape

(3, 10)

In [42]:
arr1.shape

(2, 15)

In [43]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [44]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.sum(axis=0)

array([12, 15, 18])

In [46]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [47]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [48]:
arr.flat

In [49]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [50]:
arr.ndim

2

In [51]:
lspace.ndim

1

In [52]:
arr.argmax()

np.int64(8)

In [53]:
arr.argmin()

np.int64(0)

In [54]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [55]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [56]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [57]:
ar = np.array([[1,2,1],[4,5,0],[0,1,2]])

In [58]:
arr + ar

array([[ 2,  4,  4],
       [ 8, 10,  6],
       [ 7,  9, 11]])

In [59]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar

array([[1, 2, 1],
       [4, 5, 0],
       [0, 1, 2]])

In [61]:
ar +arr

array([[ 2,  4,  4],
       [ 8, 10,  6],
       [ 7,  9, 11]])

In [62]:
ar * arr

array([[ 1,  4,  3],
       [16, 25,  0],
       [ 0,  8, 18]])

In [63]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [64]:
arr.sum()

np.int64(45)

In [65]:
ar.sum()

np.int64(16)

In [66]:
arr.max()

np.int64(9)

In [67]:
ar.min()

np.int64(0)

In [68]:
np.count_nonzero(ar)

np.int64(7)

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 1, 2]))

In [70]:
ar


array([[1, 2, 1],
       [4, 5, 0],
       [0, 1, 2]])

In [71]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [72]:
ar = np.random.randint(3,10,)
ar

7

In [73]:
arr = np.array([[1, 2, 1],
       [4, 5, 0],
       [0, 1, 2]])
arr

array([[1, 2, 1],
       [4, 5, 0],
       [0, 1, 2]])

In [74]:
arr.sum(axis =0)

array([5, 8, 3])

In [75]:
ar = np.arange(1,31).reshape(6,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [76]:
ar[3: , 3: ]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [77]:
ar[0]

array([1, 2, 3, 4, 5])

In [78]:
ar[0 , :]

array([1, 2, 3, 4, 5])

In [79]:
ar[:, 2:4]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29]])

In [80]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
bool_index = ar % 2 != 0
bool_index


array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [82]:
arr = ar[bool_index]
arr

array([1, 3, 5, 7, 9])

# MATHEMATICAL OPERATIONS 

In [83]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([10,20,30,40,50])


In [84]:
ar1

array([1, 2, 3, 4, 5])

In [85]:
ar2

array([10, 20, 30, 40, 50])

In [86]:
ar1 + ar2

array([11, 22, 33, 44, 55])

In [87]:
ar1/ar2

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [88]:
ar1//ar2

array([0, 0, 0, 0, 0])

In [89]:
ar1*ar2

array([ 10,  40,  90, 160, 250])

In [90]:
ar1 ** ar2

array([                   1,              1048576,      205891132094649,
                          0, -6776596920136667815])

In [91]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
ar1 = arr[:5]
ar2 = ar1 * 10
ar2

array([10, 20, 30, 40, 50])

In [93]:
ar1

array([1, 2, 3, 4, 5])

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
b = arr
b*2


array([44,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
b[0] = 22
b

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
c = arr.copy()

In [107]:
c[1]= 33

In [108]:
c

array([22, 33,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [112]:
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
mat1



array([[1, 2],
       [3, 4]])

In [113]:
mat2


array([[5, 6],
       [7, 8]])

In [114]:
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [115]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [116]:
mat1.T

array([[1, 3],
       [2, 4]])

In [117]:
mat1 = np.array([1,2,3,4])
mat2 = np.array([5,6,7,8])

In [118]:
mat1

array([1, 2, 3, 4])

In [119]:
mat2

array([5, 6, 7, 8])

In [120]:
np.vstack((mat1,mat2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [121]:
np.hstack((mat1,mat2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
np.column_stack((mat1,mat2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])