ROUND 2 — One array, many operations

Create just this:

arr = np.array([10, 20, 30, 40, 50])

Now give yourself questions.

For example:

Basic
Find the first element.
Find the last element.
Get [20, 30, 40].
Reverse the array.
Find the maximum.
Find the minimum.
Find the mean.
Find the standard deviation.
Find the index of the maximum.
Add 5 to every element.

Do not write the function name beside the question.

That's important.

You should force your brain to decide:

"What NumPy tool do I need?"

🟢 ROUND 3 — 2D arrays

Now create:

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

This is where your NumPy understanding should become strong.

Try:

Indexing
first row
second column
50
last row
first two rows
last two columns
middle element
Properties
shape?
ndim?
size?
Operations

Find:

total sum
mean of entire array
maximum
minimum

Then comes the most important concept:

axis

Try:

Find the sum of each row.

Then:

Find the sum of each column.

Then:

Find the mean of each row.

Then:

Find the maximum of each column.

If you can confidently understand axis=0 and axis=1, your NumPy skills will improve a LOT.

🟢 ROUND 4 — Boolean masking + where

This is extremely important for data science.

Take:

arr = np.array([10, 25, 40, 15, 60, 5])

Solve:

1.

Get all values greater than 20.

2.

Get all values between 10 and 40.

3.

Get all even numbers.

4.

Replace values greater than 30 with 0.

5.

Replace values less than 20 with -1.

6.

Find how many values are greater than 20.

You'll naturally use things like:

arr > 20
arr[arr > 20]

and eventually:

np.where(...)

That's much better than simply memorizing "np.where = condition".

🟢 ROUND 5 — Reshaping

Take:

arr = np.arange(1, 13)

Now practice:

1 × 12
2 × 6
3 × 4
4 × 3
6 × 2
12 × 1

using reshape().

Then answer:

What happens to arr.size after reshaping?

This teaches you that:

reshape changes the structure, not the number of elements.

Then learn:

flatten()
ravel()
.T
transpose()

You don't need to memorize differences immediately. Just understand what problem each solves.

🟢 ROUND 6 — Broadcasting

This deserves its own practice.

Start with:

arr = np.array([1, 2, 3, 4])

Try:

arr + 10
arr * 2
arr - 5

Then:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

Try:

arr + 10

Then:

arr + np.array([10, 20, 30])

And then deliberately create an incompatible shape and see the error.

Understanding why broadcasting works is much more valuable than memorizing the word.

🟢 ROUND 7 — Copy vs View

You already have this in your notes, so test it.

a = np.array([1, 2, 3])
b = a

Change b.

What happens to a?

Then:

a = np.array([1, 2, 3])
b = a.copy()

Change b.

What happens to a?

Then investigate slicing:

a = np.array([1, 2, 3, 4, 5])
b = a[1:4]

This is worth understanding because views vs copies can cause very confusing bugs later.

🟢 ROUND 8 — Matrix operations

Your notes have started this, so now practice it.

Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Try:

A + B
A * B
A @ B

And ask yourself:

Why is A * B different from A @ B?

That distinction is very important for ML/math.

🟢 ROUND 9 — Stacking + splitting

You have already studied this.

Don't reread it.

Instead, make two arrays and figure out:

I want these two arrays joined vertically. What do I use?

Then:

horizontally?

Then:

I want to split this array into 3 pieces. What do I use?

This is how you make the functions stick.

5. Then do a final "NumPy challenge"

This is the most important part.

At the end, take:

marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])

Imagine:

Rows = students
Columns = subjects

Now solve things like:

Find the total marks of every student.
Find the average marks of every student.
Find the average of every subject.
Find the highest mark in each subject.
Find the student-wise maximum.
Find all marks above 80.
Replace marks below 60 with 0.
Find the position of the highest mark.
Add 5 bonus marks to every subject.
Reshape another suitable array and perform an operation with marks.
Find which students have an average above 75.
Sort the students based on their total marks.

This one exercise will revise a huge portion of your NumPy.

In [1]:
import numpy as np

# Round 1

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr = np.arange(1,10)

In [5]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr.ndim

1

In [7]:
arr.size

9

In [8]:
arr.shape

(9,)

In [9]:
arr.dtype

dtype('int64')

In [10]:
ar = np.zeros((2,3))
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ar = np.ones((2,3))
ar

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [13]:
np.random.rand(10)

array([0.47648665, 0.25064754, 0.2758368 , 0.78902953, 0.28845108,
       0.85336021, 0.786694  , 0.9897442 , 0.99516552, 0.13526202])

In [14]:
np.random.randn(4)

array([ 0.90953873, -0.34474606, -0.36878097,  1.14054263])

In [15]:
np.random.randint(7)

3

In [16]:
np.random.randint(7)

0

In [17]:
np.random.randint(7)

2

In [18]:
np.random.randint(1,7,3)

array([2, 5, 2], dtype=int32)

In [19]:
np.random.randint(1,10,10)

array([5, 1, 6, 1, 2, 5, 5, 3, 4, 9], dtype=int32)

In [20]:
np.random.random()

0.24164374797862764

In [21]:
np.random.random(10)

array([0.90151977, 0.33282169, 0.63265711, 0.85097703, 0.16756822,
       0.40783125, 0.27671023, 0.79499035, 0.21649428, 0.72640794])

In [22]:
np.random.normal(5)

4.744361838186146

# Round 2

In [23]:
arr = np.array([10, 20, 30, 40, 50])

In [24]:
arr[:1]
# first element

array([10])

In [25]:
# last element
arr[4:]

array([50])

In [26]:
arr[1:4]

array([20, 30, 40])

In [27]:
arr.max()

np.int64(50)

In [28]:
arr.min()

np.int64(10)

In [29]:
arr.mean()

np.float64(30.0)

In [30]:
arr.std()

np.float64(14.142135623730951)

In [31]:
arr.argmax()

np.int64(4)

In [32]:
arr + 5

array([15, 25, 35, 45, 55])

In [33]:
arr = np.array([10, 20, 30, 40, 50])

In [34]:
rev_arr = arr[::-1]
rev_arr

array([50, 40, 30, 20, 10])

# Round 3

In [35]:
array = np.array([ [10, 20, 30], [40, 50, 60], [70, 80, 90] ])
array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [36]:
array[0]

array([10, 20, 30])

In [37]:
array[1]

array([40, 50, 60])

In [38]:
array[1,1]

np.int64(50)

In [39]:
array[2]

array([70, 80, 90])

In [40]:
array[:2,:]

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
array[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [42]:
array.sum()

np.int64(450)

In [43]:
array.mean()

np.float64(50.0)

In [44]:
array.max()

np.int64(90)

In [45]:
array.sum(axis = 1)

array([ 60, 150, 240])

In [46]:
array.sum(axis = 0)

array([120, 150, 180])

In [47]:
array.mean(axis = 0)

array([40., 50., 60.])

In [48]:
array.max(axis = 0)

array([70, 80, 90])

In [49]:
array.min(axis = 1)

array([10, 40, 70])

# Round 4

In [50]:
arr = np.array([10, 25, 40, 15, 60, 5])

In [51]:
arr.sort()
# NOT RECOMMENDED FOR NUMBERS ABOVE 20

In [52]:
arr

array([ 5, 10, 15, 25, 40, 60])

In [53]:
arr[3:]

array([25, 40, 60])

In [54]:
greater_than_20 = arr> 20

In [55]:
arr[greater_than_20]

array([25, 40, 60])

In [56]:
arr[(arr>= 10) & (arr <= 40)]

array([10, 15, 25, 40])

In [57]:
arr[arr % 2 == 0]

array([10, 40, 60])

In [58]:
 arr[arr > 30] = 0

In [59]:
print(arr)

[ 5 10 15 25  0  0]


In [60]:

arr

array([ 5, 10, 15, 25,  0,  0])

In [63]:
arr[arr<20].size

5

# Round 5

In [64]:
arr = np.arange(1,13)

In [65]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [67]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [69]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
arr.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
arr.transpose()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Round 6

In [73]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [74]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
arr +10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [78]:
arr + np.array([1,2,3,4])

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [79]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [80]:
b = arr

In [81]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
b + 2
# HERE, B IS NOT CHANGING. INSTEAD ITS RETURNING A NEW ARRAY B+2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [85]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
b[0,0] = 99

In [87]:
b

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [88]:
arr

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8]])

# **Shallow and Deep copy**

In [89]:
arr = np.array([10, 20, 30, 40])

In [90]:
b = arr.view()

In [91]:
b[3] = 999

In [92]:
b

array([ 10,  20,  30, 999])

In [93]:
arr

array([ 10,  20,  30, 999])

In [94]:
arr = np.array([2, 4, 6, 8])

In [95]:
c = arr.copy()

In [96]:
c[0] = 100
c

array([100,   4,   6,   8])

In [97]:
arr

array([2, 4, 6, 8])

# Round 8

In [98]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [100]:
A + B


array([[ 6,  8],
       [10, 12]])

In [101]:
A @ B

array([[19, 22],
       [43, 50]])

In [102]:
A * B

array([[ 5, 12],
       [21, 32]])

# **Numpy final ques practice**

In [103]:
marks = np.array([
    [78, 85, 92],
    [65, 72, 80],
    [90, 88, 95],
    [55, 60, 70]
])